version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres  
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:ro
    env_file:
      - ./.env
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data 

volumes:
  postgres-db:  
